application: gopherize-com
version: 1
runtime: go
api_version: go1.8
threadsafe: true
automatic_scaling:
  min_idle_instances: 0
  max_idle_instances: 1
handlers:
- url: /.*
  script: _go_app
  secure: always
